### PR TITLE
Support for Latte v3

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by dg** [comment]
I think it's ready to merge.

**Comment by hrach** [comment]
Thanks for this contribution. 

First of all, it seems that some of dependencies is holding latte back. None of PHPStan test is using Latte 3, so the new code is not tested. 
Second, I guess we either remove those prefer-lowest or rather add phpstan `@phpstan-ignore-line` supressions for the old code path.

**Comment by JanTvrdik** [comment]
> First of all, it seems that some of dependencies is holding latte back. 

That was due to Latte 3 not being stable at the time the pipeline run.

---

I think overall better solution would be to stop using the macro.

**Comment by JanTvrdik** [comment]
https://github.com/nextras/mail-panel/pull/37

**Comment by dg** [comment]
Function is better, closing.

**Pull request closed without merging**
