### PR TITLE
SVG icon on panel

### PR DESCRIPTION
**Pull request by irkallacz**
Better looking icon, more compatible with the rest of Tracy panels. Icon is based on https://commons.wikimedia.org/wiki/File:Email_Silk.svg but remixed and simplified.

### CODE REVIEW

**Comment by hrach** [comment]
post some screenshot please :)

**Comment by irkallacz** [comment]
[Screenshot 1](https://lh3.googleusercontent.com/ZAF2I1_rLQgstBXpEs1tA2RIeg-3nj7w1USbei3f_SrM4o-yEtSRNEwsqpVPqydbFodxoXQuheTY9UqXwd9wBx1N-cR1RYy9KXacr5XT3_qCBwKnQrA8vkkptEmQXeZqC9o7bC0gNVrqzlb4_ZmkuEgilkFTVNMiP0YcH_OJcN8LW6c677fx63jV2IWtYRir7ZiAS2AU3wok_tNtaLIsBVi6Djxg5dj1_a66J3NBp_vPKIK4_-EeRMeFDNxm8ZY0l2X0mStncAaNPdbFao8PnX51xiw9k7lqWGT1q0vls4Tgset55u3PqzehokgZZtpxbN0rC9qziWcMCUH8f1a0na-75nvVroonDW5nCInhf5-zB9HMcKwebLYWEUNRaHd85FU2vuUYgzRWeRJyUNtXtqqgGtogfN5ggkOIsqb3SXMiqKNhl2RZpm-8a4Bj-ChNqSiHGY5awaeXbvfZWK3RuN6mPmUtx8PMym8dtc4Y1jP1_X_wLSs1LnjX_-nbooZIw5dn1i0B8wCd9Y1h60hTg76VIBkbf4t2bZA6fMx4oLU=w1237-h567-no)  - normal 
[Screenshot 2](https://lh3.googleusercontent.com/j2oaz92OxezyCbd-2vCocP9c2ydnYbTF_-C2itkxJiIDmXj8kDjzVUERG3hH_U5My9f8mtcJhS9sA8fgCHdSCRa0_oRqCCmz_VJJQav4V1RRJB2Ky-nfoVl1R01LgSWhHpRjhQ8fksar7gxkCE52yfhgKlc3qV_n98L9seq_Tf35Ud6DJkSxUpFhr4aufw3YGMcVoXBRd06sLUjIg2YcSSQFJCJnHYs4vLbOMMfhqaodNdGAMPdgGj6WAfqSyUVAjDHpknI5GokSeMkK93pxXSJGLwsTGNHcDqn9mR7ZRvYy4eCS1jY_ooWKH6vDP7PnIBlQbW_8JYp5VGCdXqFpxR0BP6hk3TJJkrigNx4zoufMVVSJwxICu3if31SvpV6FyKFE0n7ORmAqiKSBkGzI4uTusSiztaYHutXUIMBXMVLM7OvRPsDOEXHagiq4POZt53SVYQQcZqaqQP36wFIHwCbDU5FyBGrw5QXn-gHavkr_eHam2Pa6GSdPcs_WosARhOwvoEFW5RosCyu5HhAl-KgUtUkNNVwVy61KX--n0MI=w1007-h481-no) - page max zoom in

**Comment by hrach** [comment]
Probably,  I don't have right to view them :)

**Comment by irkallacz** [comment]
OK sorry try it now.

**Comment by hrach** [comment]
Could you remove the inner background and let there only the lines? :)

**Comment by irkallacz** [comment]
It is not that easy. Image consist of 3 overlapping rectangles and two paths and their backgrounds are necessary to hide some parts of image.

**Comment by hrach** [comment]
Ok :) thanks!

**Pull request merged**
